FROM buildpack-deps:jessie-scm

# gcc for cgo
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    gcc \
    libc6-dev \
    make \
    pkg-config \
  && rm -rf /var/lib/apt/lists/*

ENV GOLANG_1_7_VERSION {{.GO_1_7_VERSION}}
ENV GOLANG_1_7_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_1_7_VERSION.linux-amd64.tar.gz
ENV GOLANG_1_7_DOWNLOAD_SHA256 {{.GO_1_7_LINUX_AMD64_SHA256}}

ENV GOLANG_1_8_VERSION {{.GO_1_8_VERSION}}
ENV GOLANG_1_8_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_1_8_VERSION.linux-amd64.tar.gz
ENV GOLANG_1_8_DOWNLOAD_SHA256 {{.GO_1_8_LINUX_AMD64_SHA256}}

RUN curl -fsSL "$GOLANG_1_7_DOWNLOAD_URL" -o golang.tar.gz \
  && echo "$GOLANG_1_7_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
  && tar -C /usr/local -xzf golang.tar.gz \
  && rm golang.tar.gz \
  && mv /usr/local/go /usr/local/go-1.7

RUN curl -fsSL "$GOLANG_1_8_DOWNLOAD_URL" -o golang.tar.gz \
  && echo "$GOLANG_1_8_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
  && tar -C /usr/local -xzf golang.tar.gz \
  && rm golang.tar.gz \
  && mv /usr/local/go /usr/local/go-1.8

RUN ln -s /usr/local/go-1.8 /usr/local/go

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

COPY go-wrapper /usr/local/bin/
