FROM golang:{{.CURRENT_GO_VERSION}}

RUN apt-get update
RUN apt-get -y install rpm
RUN apt-get -y install ruby-dev
RUN apt-get -y install rubygems
RUN gem install fpm

ENV USER_ID 1000
RUN adduser gouser --uid $USER_ID
RUN chown -R gouser /go

COPY ./run-as-gouser.sh /
RUN chmod +x /run-as-gouser.sh
