FROM golang:{{.GO_VERSION}}

ENV DOCKER_VERSION {{.DOCKER_VERSION}}
RUN curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
RUN tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
RUN  mv /tmp/docker/* /usr/bin
