FROM {{Tag "go-darwin-linux-no-cgo" 0 0}}

ENV VERSION {{.DOCKER_VERSION}}
RUN curl -fsSL get.docker.com -o get-docker.sh
RUN sh get-docker.sh

ENV GROUP_ID 1000
RUN groupadd --gid $GROUP_ID gogroup

ENV USER_ID 1000
RUN useradd --uid $USER_ID --gid $GROUP_ID gouser
RUN chown -R gouser /go

RUN mkdir -p /home/gouser
RUN chown -R gouser /home/gouser

RUN apt-get update
RUN apt-get -y install rpm
RUN apt-get -y install ruby-dev
RUN apt-get -y install rubygems
RUN gem install fpm

USER gouser:gogroup
