FROM golang:{{.CURRENT_GO_VERSION}}-alpine

RUN apk update && apk add --no-cache bash git openssl openssh

RUN mv /usr/local/go /usr/local/go-{{.CURRENT_GO_VERSION}}
RUN ln -s /usr/local/go-{{.CURRENT_GO_VERSION}} /usr/local/go

ENV GOLANG_PREVIOUS_SRC_URL https://golang.org/dl/go{{.PREVIOUS_GO_VERSION}}.src.tar.gz
ENV GOLANG_PREVIOUS_SRC_SHA256 {{.PREVIOUS_GO_SRC_SHA256}}

# https://golang.org/issue/14851
COPY no-pic-1.8.patch /
# https://golang.org/issue/17847
COPY 17847.patch /

RUN set -ex \
  && apk add --no-cache --virtual .build-deps \
    bash \
    gcc \
    musl-dev \
    openssl \
    go \
  \
  && export GOROOT_BOOTSTRAP="$(go env GOROOT)" \
  \
  && cd / \
  && wget -q "$GOLANG_PREVIOUS_SRC_URL" -O golang.tar.gz \
  && echo "$GOLANG_PREVIOUS_SRC_SHA256  golang.tar.gz" | sha256sum -c - \
  && tar -C /tmp -xzf golang.tar.gz \
  && rm golang.tar.gz \
  && mv /tmp/go /usr/local/go-{{.PREVIOUS_GO_VERSION}} \
  && cd /usr/local/go-{{.PREVIOUS_GO_VERSION}}/src \
  && patch -p2 -i /no-pic-1.8.patch \
  && ./make.bash \
  \
  && rm -rf /*.patch \
  && apk del .build-deps
