FROM {{Tag "go-darwin-linux-no-cgo" 0 0}}

RUN mkdir -p /opt/jdk && \
    curl https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz -o /opt/jdk-11.0.1.tgz && \
    tar -xvf /opt/jdk-11.0.1.tgz --strip-components=1 -C /opt/jdk
    
ENV JAVA_HOME /opt/jdk
ENV PATH "$PATH:$JAVA_HOME/bin"
